### ISSUE TITLE
AudioVolume(Down|Up|Mute) shouldn't be changed from Volume(Down|Up|Mute)?

### ISSUE THREAD

**Issue by masayuki-nakano** [w3c/uievents-key#14]
Counter part of this issue is, https://github.com/w3c/uievents-code/issues/8

If key names of Volume(Down|Up|Mute) should have "Audio" prefix, code values of them should have "Audio" prefix too for consistency. However, it's not good for backward compatibility since IE and Firefox already implemented .key with old values (i.e., without "Audio" prefix).

Is it really better to change the names than keeping backward compatibility?

**Comment by masayuki-nakano** [comment]
@garykac I want to know your decision about this issue as soon as possible.

**Comment by garykac** [comment]
The change was made to clearly distinguish between AudioVolume\* and MicrophoneVolume\* values. Esp. for VolumeMute, where it's not obvious whether that's audio mute or microphone mute.

The backwards compat is not an issue (yet) because |key| and |code| are not widely adopted yet. IE/Edge already knows that it will need to make a bunch of incompatible changes to their |key| values.
