### ISSUE TITLE
Implementation report

### ISSUE THREAD

**Issue by LJWatson** [w3c/uievents-key#45]
Is there an implementation report for this spec? We'll need something of the sort to exit CR.

**Comment by masayuki-nakano** [comment]
Not an official document, but here is my spreadsheet to show current implementation of each browser:
https://docs.google.com/spreadsheets/d/1YB4M5Y5BWSn-7FX7pXFNbLtDDGzQ0noUTIo-YSqyRzc/edit#gid=0

**Comment by garykac** [comment]
I created an initial draft implementation report:
https://w3c.github.io/uievents-key/impl-report.html

**Comment by LJWatson** [comment]
It looks like there are gaps in the implementation report for testing with things other than browsers (TV remotes etc.). Do we have implementations for all devices?

**Comment by LJWatson** [comment]
b

**Comment by xfq** [comment]
I had a look at the implementation report. WebKit now supports `KeyboardEvent.key`[1]. It's shipped in Safari too[2]. Here's my manual test results in Safari 11.0.3 on 10.13.3:

* In Unnamed key Attribute Values, all `key` attribute values are supported.

* In Standard Named Keys, I'm not sure how to test "Unidentified".

* In Modifier Keys, `key` attribute values other than "AltGraph", "NumLock", and "ScrollLock" are supported. My keyboard does not contain these three keys so I'm not able to test them.

* In Whitespace Keys, all `key` attribute values are supported.

* In Navigation Keys, all `key` attribute values are supported (some of them are emulated by fn + various keys on the keyboard).

* In Editing Keys, "Backspace" and "Delete"	are supported. Not sure about "Insert".

* In UI Keys, "Escape" is supported. I don't have other keys.

* I haven't tested Device Keys because of the lack of the "PrintScreen"	key.

* In General-Purpose Function Keys, all `key` attribute values are supported.

* I haven't tested Editing and IME Named Keys because of the lack of these keys.

* In Device-specific Named Keys, "Fn" is not supported (in all three browsers on macOS). Not sure about other keys (including Modifier Keys, Legacy modifier keys, UI Keys, Device Keys, General-Purpose Function Keys, Multimedia Keys, Multimedia Numpad Keys, Audio Keys, Speech Keys, Application Keys, Browser Keys, Mobile Phone Keys, TV Keys, and Media Controller Keys) because of the lack of these keys/devices.

I don't have a Windows machine and therefore I'm not able to provide the test results for Microsoft Edge.


-----

Test code:

```javascript
window.addEventListener("keydown", function (event) {
    let out = "KeyboardEvent: key='" + event.key + "' | code='" + event.code + "'";
    console.log(out);
}, true);
```

-----

Links:

[1] https://bugs.webkit.org/show_bug.cgi?id=36267
[2] https://webkit.org/blog/6987/release-notes-for-safari-technology-preview-15/

**Comment by xfq** [comment]
Looks like some features don't meet the CR exit criteria (i.e., two independent implementations).

**Comment by xfq** [comment]
Here are some useful comments from @frivoal: https://lists.w3.org/Archives/Public/public-webapps/2018JanMar/0028.html

-----

Summary:

* Link to test files, preferably by linking each entry in the result tables to the corresponding test if possible;
* If automated testing is not possible, file bugs against web-platform-tests and/or WebDriver, and use manual tests for now;
* Distinguish different kinds of failures in the test results;
* Rename "Yes" to "Pass";
* Add a summary of the test results;
* State why it is judged acceptable to move to PR for features with less than 2 "Yes"/"Pass".

**Comment by garykac** [comment]
The implementation report has been updated:
https://w3c.github.io/uievents-key/impl-report.html

**Comment by marcoscaceres** [comment]
Closing as done.
